#!/bin/sh

if [[ "$1" =~ [0-9]+.[0-9]+.[0-9]+ ]]
then
  VERSION=$1
  echo "About to update to version $VERSION. CTRL-C to interrupt. ENTER to proceed."
  read FOO
else
  echo "Invalid version number specified. Exiting."
  exit 1
fi

sed -i '' -E "/CLIENT_ID/s/[0-9]+\.[0-9]+\.[0-9]+/$VERSION/g" lib/DefensioWP.php
sed -i '' -E "/Version: /s/[0-9]+\.[0-9]+\.[0-9]+/$VERSION/g" defensio.php
sed -i '' -E "/Stable tag:/s/[0-9]+\.[0-9]+\.[0-9]+/$VERSION/g" readme.txt
DATE=`date "+%m-%d-%Y"`
sed -i '' -E "/NEXT_VERSION/s/NEXT_VERSION/$VERSION ($DATE)/g" readme.txt

git add lib/DefensioWP.php
git add defensio.php
git add readme.txt
git ci -m "Increment version number to $VERSION"
git push

echo "Updated files to $VERSION."

